### ISSUE TITLE
Question about training the critic

### ISSUE THREAD

**Issue by AlexanderGri** [yalidu/liir#16]
First of all, thank you for interesting paper and published code!

I have a question regarding the training of the critics. As far as I understand you use state value functions and train them off-policy through temporal difference learning (https://github.com/yalidu/liir/blob/master/src/learners/liir_learner.py#L224). Could you please clarify how to manage expectation over reward in temporal difference target for state value function if states/actions come from different policy? It seems to me that you need to sample from current policy, take the corresponding action and feed it to unknown reward function. Am I missing something?

**Comment by yalidu** [comment]
Hi, there is one TD target based on team reward and n TD target based on individual proxy reward for each agent.
