### ISSUE TITLE
Some Questions of your paper

### ISSUE THREAD

**Issue by hhhusiyi-monash** [yalidu/liir#5]
Hi,

Thanks for your awesome work on MARL.

Here I still some questions after reading your paper.

As for equation 6, i am confused why here the Advantage Function is a decentralized critic for each agent but not centralized critic defined in equation 1 following rule CLDE(Centralized learning with decentralized execution). I guess in equation 6 the 'u' and 's' should be bold.

Besides in Algorithm 1 line 5 , i believe the replacement of equation 8 miss a policy with a log function.

Wonder if I misunderstand something and could your check for me pls? 

Best.
C

**Comment by yalidu** [comment]
Hi,

For eq.(6), thanks for pointing this out. 'u' and 's' in A^proxy should be bold, since r^ex depends on the global state, though r^in needs only local observations.
For line 5 in algorithm 1, I guess it is correct. You may find the following form useful.


Best,
Yali Du

**Comment by yalidu** [comment]
Hi,

For eq.(6), thanks for pointing this out. 'u' and 's' in A^proxy should be bold, since r^ex depends on the global state, though r^in needs only local observations.
For line 5 in algorithm 1, it is correct. You may find the following link useful.
https://medium.com/@jonathan_hui/rl-importance-sampling-ebfb28b4a8c6

Best,
Yali

**Comment by hhhusiyi-monash** [comment]
Many Thanks.

![image](https://user-images.githubusercontent.com/67732859/88872661-45961580-d24d-11ea-9d0e-f1dc5330dc63.png)
I think the gradient should be like this. The gradient should be from θ‘ to update the θ, following the spirit of meta learning.

Best
C

**Comment by hhhusiyi-monash** [comment]
By the way could you tell me the meaning of 'update' function in 'EpisodeBatch' at file 'episode_buffer.py', especially the field of 'filled' in transition data. I can't figure out why we should mask out the data with 'filled' == 0 in learning procedure.

It would be a great help if you explain for me.
Many Thanks

Best
C

**Comment by yalidu** [comment]
https://github.com/oxwhirl/pymarl/issues/55

**Comment by yalidu** [comment]
Hi, Please check these two issues, which might answer your questions.
https://github.com/oxwhirl/pymarl/issues/16
https://github.com/oxwhirl/pymarl/issues/55
