### ISSUE TITLE
Where is the codes for Visualizing the Learned Intrinsic Reward?

### ISSUE THREAD

**Issue by GuiyangLuo** [yalidu/liir#6]
Hi,

Thanks for your awesome work on MARL.

Where are the codes for Visualizing the Learned Intrinsic Reward? Did you Visualize it by Replay? How to connect it with intrinsic reward?

**Comment by yalidu** [comment]
In the testing time, you can pause after each step to save the intrinsic reward and the visualized image.

**Comment by GuiyangLuo** [comment]
Thanks so much. By the way, the LIIR algorithm achieves a poor performance on the hard scenario (e.g., 5m_vs_6m). Does it have a higher variance?

**Comment by yalidu** [comment]
I did not test on the antisymmetric scenarios. There is another paper applying LIIR to other different maps. 
https://arxiv.org/pdf/2007.02529.pdf

**Comment by GuiyangLuo** [comment]
Appreciate it  so much! Thanks



luoguiyang111@gmail.com
 
From: Yali Du
Date: 2020-09-16 14:49
To: yalidu/liir
CC: GuiyangLuo; Author
Subject: Re: [yalidu/liir] Where is the codes for Visualizing the Learned Intrinsic Reward? (#6)
I did not test on the antisymmetric scenarios. There is another paper applying LIIR to other different maps.
https://arxiv.org/pdf/2007.02529.pdf
